const WorkStylesQuest = [
    {
      quadrant: 1,
      title: "Nhóm đặc điểm 1",
      description: "Khoanh tròn những từ mô tả bạn tốt nhất trong ô này.",
      traits: [
        { trait: "Nhiệt tình", score: 5 },
        { trait: "Chấp nhận rủi ro", score: 1 },
        { trait: "Sáng tạo", score: 5 },
        { trait: "Người tạo động lực", score: 1 },
        { trait: "Năng động", score: 1 },
        { trait: "Rất hoạt ngôn", score: 1 },
        { trait: "Lý tưởng", score: 1 },
        { trait: "Thân thiện", score: 1 },
        { trait: "Hòa nhập dễ dàng trong nhóm", score: 1 },
        { trait: "Yêu thích sự vui vẻ", score: 1 },
        { trait: "Thích được yêu thích", score: 1 },
        { trait: "Thích sự thay đổi", score: 1 },
        { trait: "Thích sự đa dạng", score: 1 },
        { trait: "Tự phát", score: 5 },
        { trait: "Sáng tạo - ý tưởng mới", score: 5 },
        { trait: "Hướng đến nhóm", score: 1 },
        { trait: "Lạc quan", score: 1 },
        { trait: "Truyền cảm hứng", score: 1 },
        { trait: "Tiếng cười lan tỏa", score: 1 },
      ],
    },
    {
      quadrant: 2,
      title: "Nhóm đặc điểm 2",
      description: "Khoanh tròn những từ mô tả bạn tốt nhất trong ô này.",
      traits: [
        { trait: "Nhạy cảm về cảm xúc", score: 5 },
        { trait: "Trung thành", score: 5 },
        { trait: "Bình tĩnh", score: 1 },
        { trait: "Điềm tĩnh", score: 1 },
        { trait: "Không yêu cầu cao", score: 1 },
        { trait: "Dễ dãi", score: 1 },
        { trait: "Tránh đối đầu", score: 1 },
        { trait: "Thiếu quyết đoán", score: 1 },
        { trait: "Thích thói quen", score: 1 },
        { trait: "Không thích thay đổi", score: 1 },
        { trait: "Biết ơn", score: 5 },
        { trait: "Hài hước nhẹ nhàng", score: 1 },
        { trait: "Hợp tác", score: 5 },
        { trait: "Thấu hiểu", score: 5 },
        { trait: "Chu đáo", score: 1 },
        { trait: "Quan tâm", score: 1 },
        { trait: "Kiên nhẫn", score: 1 },
        { trait: "Khoan dung", score: 1 },
        { trait: "Lắng nghe tốt", score: 1 },
        { trait: "Người hòa giải", score: 1 },
      ],
    },
    {
      quadrant: 3,
      title: "Nhóm đặc điểm 3",
      description: "Khoanh tròn những từ mô tả bạn tốt nhất trong ô này.",
      traits: [
        { trait: "Thích hướng dẫn", score: 1 },
        { trait: "Chính xác", score: 1 },
        { trait: "Nhất quán", score: 1 },
        { trait: "Có kiểm soát", score: 1 },
        { trait: "Kín đáo", score: 1 },
        { trait: "Dễ đoán", score: 1 },
        { trait: "Logic", score: 5 },
        { trait: "Kỷ luật", score: 5 },
        { trait: "Thực tế", score: 1 },
        { trait: "Tận tâm", score: 1 },
        { trait: "Cầu toàn", score: 5 },
        { trait: "Tinh ý", score: 1 },
        { trait: "Chi tiết", score: 5 },
        { trait: "Phân tích", score: 1 },
        { trait: "Tò mò", score: 1 },
        { trait: "Chính xác", score: 1 },
        { trait: "Kiên trì", score: 1 },
        { trait: "Theo lịch trình", score: 1 },
        { trait: "Nhạy cảm", score: 1 },
        { trait: "Khách quan", score: 5 },
      ],
    },
    {
      quadrant: 4,
      title: "Nhóm đặc điểm 4",
      description: "Khoanh tròn những từ mô tả bạn tốt nhất trong ô này.",
      traits: [
        { trait: "Thích quyền lực", score: 1 },
        { trait: "Dẫn đầu", score: 5 },
        { trait: "Tự tin", score: 5 },
        { trait: "Quyết tâm", score: 1 },
        { trait: "Kiên quyết", score: 1 },
        { trait: "Doanh nhân", score: 1 },
        { trait: "Thích thử thách", score: 5 },
        { trait: "Cạnh tranh", score: 5 },
        { trait: "Hướng đến kết quả", score: 5 },
        { trait: "Hiệu quả", score: 1 },
        { trait: "Táo bạo", score: 1 },
        { trait: "Có mục đích", score: 1 },
        { trait: "Hướng đến mục tiêu", score: 1 },
        { trait: "Thích phiêu lưu", score: 1 },
        { trait: "Cứng cỏi", score: 1 },
        { trait: "Độc lập", score: 1 },
        { trait: "Tự lực", score: 1 },
        { trait: "Kiểm soát", score: 1 },
        { trait: "Kiên trì", score: 1 },
        { trait: "Quả quyết", score: 5 },
      ],
    },
  ];
  
  export default WorkStylesQuest;
  